apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: mern-example
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 3000
      nodePort: 3000
  selector:
    app: web
    tier: frontend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-claim
  labels:
    app: mern-example
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  labels:
    app: mern-example
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mern-example
        tier: frontend
    spec:
      containers:
      - image: .
        name: web
        env:
        - name: MONGO_URL
          value: mongodb://mongo/comments
        ports:
        - containerPort: 3000
          name: web
        volumeMounts:
        - name: web
          mountPath: /home:rw
      volumes:
      - name: web
        persistentVolumeClaim:
          claimName: web-claim